/**
 * Prayana AI shared type definitions.
 * Re-exports all types from domain modules.
 */

// User & Auth
export type {
  Currency,
  Language,
  TravelStyle,
  BudgetRange,
  Interest,
  AuthMethod,
  ActiveFeature,
  Gender,
  MembershipTier,
  DevicePlatform,
  FcmToken,
  NotificationPreferences,
  UserPreferences,
  UserStats,
  AuthMethodUsage,
  ConversionEvent,
  AppUsageAnalytics,
  DeviceInfo,
  AppUsage,
  PersonalInfo,
  Membership,
  EditableStats,
  FavoritePlace,
  User,
  AuthState,
  UserProfileDisplay,
  UserPublicProfile,
} from './user';

// Trip planning
export type {
  TripBudgetLevel,
  TripType,
  BudgetCategory,
  SplitType,
  CollaboratorRole,
  TripActivityCoordinates,
  TripActivity,
  TransportInfo,
  TripDay,
  TripDestination,
  CustomSplit,
  TripExpense,
  OfflineMember,
  SettledTransaction,
  BudgetCategories,
  Collaborator,
  ActiveEditor,
  FieldPresenceUser,
  FieldPresenceMap,
  TripSetup,
  TripState,
  TripSavePayload,
} from './trip';

// Activity marketplace
export type {
  ActivityCategory,
  DurationUnit,
  PriceType,
  CancellationPolicy,
  ActivityStatus,
  RefundMethod,
  ActivityDocumentStatus,
  DiscountType,
  VariantName,
  Coordinates,
  ActivityImage,
  AvailabilitySlot,
  ActivityDuration,
  ActivityGroupSize,
  ActivityLocation,
  BulkDiscount,
  SeasonalPricing,
  DateOverride,
  ActivityPricing,
  InstantBookingConfig,
  RefundRule,
  CancellationPolicyRules,
  ActivityRatingDistribution,
  ActivityRating,
  ActivityStats,
  ActivityDocument,
  SafetyDeclarations,
  ActivityListing,
  VariantPricing,
  VariantCapacity,
  VariantImage,
  ActivityVariant,
  ReviewReply,
  ReviewerInfo,
  ActivityReview,
  TimeSlot,
} from './activity';

// Bookings & Payments
export type {
  BookingStatus,
  PaymentMethod,
  PaymentStatus,
  StatusChangedBy,
  ParticipantGender,
  ChildGender,
  PaymentGateway,
  TransactionStatus,
  TransactionMethod,
  PayoutStatus,
  QualityTier,
  CommissionSource,
  BookingTimeSlot,
  BookingParticipants,
  CommissionBreakdown,
  AgentEarnings,
  BookingPricing,
  StatusHistoryEntry,
  BookingPayment,
  PreBookingAnswer,
  EmergencyContact,
  AdultParticipant,
  ChildParticipant,
  ParticipantDetails,
  CancellationInfo,
  ActivitySnapshot,
  Booking,
  TransactionCommission,
  AgentPayout,
  PaymentTransaction,
  MessageSender,
  MessageAttachmentType,
  MessageAttachment,
  BookingMessage,
} from './booking';

// Business accounts
export type {
  AccountType,
  VerificationStatus,
  KycTier,
  PayoutMethod,
  DocumentType,
  DocumentStatus,
  DocumentVerificationMethod,
  GstVerificationStatus,
  BusinessLocation,
  BusinessContact,
  GstDetails,
  DocumentVerificationDetails,
  DocumentExpiryAlerts,
  BusinessDocument,
  PanDetails,
  AadhaarDetails,
  FssaiDetails,
  BankDetails,
  BusinessPayout,
  CommissionOverride,
  BusinessStats,
  BusinessAccount,
  BusinessPublicProfile,
  QualityMetric,
  ResponseTimeMetric,
  CancellationRateMetric,
  CompletionRateMetric,
  CustomerRatingMetric,
  QualityScoreHistoryEntry,
  SellerQualityScore,
} from './business';

// Chat & AI
export type {
  ChatSessionStatus,
  ChatSessionView,
  ChatMessageRole,
  ChatMessageType,
  ChatMessageStatus,
  InputMethod,
  MessageSentiment,
  ChatActionType,
  DetectedIntent,
  SearchResultMetadata,
  ChatSearchResult,
  ChatSessionContext,
  SessionActionPerformed,
  SessionAnalytics,
  SessionMetadata,
  ChatSession,
  ChatSessionSummary,
  RelatedPlace,
  ChatActionTaken,
  ChatMessageContext,
  TokenUsage,
  SafetyRating,
  AiData,
  EditHistoryEntry,
  UserData,
  ChatAction,
  ChatMessageMetadata,
  ChatMessage,
} from './chat';

// API response types
export type {
  ApiResponse,
  ApiErrorResponse,
  ApiResult,
  PaginationParams,
  PaginationMeta,
  PaginatedResponse,
  SortOption,
  DateRange,
  ListFilters,
  MutationRequest,
  IdParam,
  SocketEventName,
  SocketEvent,
  CollaborationUpdate,
  HealthCheckResponse,
} from './api';
