/**
 * Share and Export API
 * Handle trip sharing, PDF export, and calendar integration
 * Adapted for React Native: removed window/document/navigator references
 * Platform-specific sharing (clipboard, native share, PDF) should be handled at the app level.
 */

import { makeAPICall } from "../apiConfig";

/**
 * Generate shareable link for a trip
 */
export async function generateShareLink(tripId, options = {}) {
  const {
    expiresIn = null, // null = never expires, or duration in days
    password = null,
    allowComments = false,
    allowEditing = false,
  } = options;

  try {
    const response = await makeAPICall('/trip/share', {
      method: 'POST',
      body: JSON.stringify({
        tripId,
        expiresIn,
        password,
        allowComments,
        allowEditing,
      }),
    });

    if (response?.success) {
      return {
        success: true,
        data: {
          shareToken: response.data.shareToken,
          // shareUrl is assembled by the app layer (which knows the deep link scheme)
          shareToken: response.data.shareToken,
          expiresAt: response.data.expiresAt,
          qrCode: response.data.qrCode, // Optional QR code image
        },
      };
    }

    return response;
  } catch (error) {
    console.error('Share link generation failed:', error);
    return {
      success: false,
      error: 'Failed to generate share link',
    };
  }
}

/**
 * Generate iCalendar (.ics) format for calendar import
 */
export function generateICalendar(trip) {
  const { name, description, startDate, endDate, days } = trip;

  // ICS format requires specific date format: YYYYMMDDTHHMMSSZ
  const formatICSDate = (date) => {
    if (!date) return '';
    const d = new Date(date);
    return d.toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
  };

  let icsContent = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//Prayana AI//Trip Planner//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
  ];

  // Add main trip event
  icsContent.push(
    'BEGIN:VEVENT',
    `DTSTART:${formatICSDate(startDate)}`,
    `DTEND:${formatICSDate(endDate)}`,
    `SUMMARY:${name || 'Trip'}`,
    `DESCRIPTION:${description || 'Generated by Prayana AI'}`,
    `UID:trip-${Date.now()}@prayanaai.com`,
    `DTSTAMP:${formatICSDate(new Date())}`,
    'END:VEVENT'
  );

  // Add individual day events
  days.forEach((day, index) => {
    const dayDate = day.date || new Date(startDate);

    day.activities?.forEach((activity, actIndex) => {
      const activityStart = new Date(dayDate);

      // Set activity times based on time slot
      const timeSlotHours = {
        morning: 9,
        afternoon: 14,
        evening: 18,
        night: 21,
      };

      activityStart.setHours(timeSlotHours[activity.timeSlot] || 9);
      activityStart.setMinutes(actIndex * 30); // Space activities 30 min apart

      const activityEnd = new Date(activityStart);
      activityEnd.setHours(activityEnd.getHours() + 2); // 2-hour default duration

      icsContent.push(
        'BEGIN:VEVENT',
        `DTSTART:${formatICSDate(activityStart)}`,
        `DTEND:${formatICSDate(activityEnd)}`,
        `SUMMARY:${activity.name}`,
        `DESCRIPTION:${activity.description || ''}`,
        `LOCATION:${activity.locationName || ''}`,
        activity.coordinates ? `GEO:${activity.coordinates.lat};${activity.coordinates.lng}` : '',
        `UID:activity-${day.dayNumber}-${actIndex}@prayanaai.com`,
        `DTSTAMP:${formatICSDate(new Date())}`,
        'END:VEVENT'
      );
    });
  });

  icsContent.push('END:VCALENDAR');

  return icsContent.filter(line => line).join('\r\n');
}

/**
 * Generate PDF HTML content (platform-specific rendering handled by apps)
 */
export function generatePDFHTML(trip) {
  const { name, description, startDate, endDate, days, destinations } = trip;

  const formatDate = (date) => {
    return new Date(date).toLocaleDateString('en-US', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
  };

  const dayColors = [
    '#06B6D4', '#8B5CF6', '#F59E0B', '#10B981',
    '#EF4444', '#3B82F6', '#EC4899', '#14B8A6'
  ];

  let html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${name || 'Trip Itinerary'}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; background: white; padding: 40px; }
    .header { text-align: center; margin-bottom: 40px; padding-bottom: 20px; border-bottom: 3px solid #06B6D4; }
    .header h1 { font-size: 36px; color: #1a1a1a; margin-bottom: 10px; }
    .header .dates { font-size: 18px; color: #666; margin-bottom: 15px; }
    .stats { display: flex; justify-content: center; gap: 40px; margin: 30px 0; padding: 20px; background: #f8f9fa; border-radius: 10px; }
    .stat-item { text-align: center; }
    .stat-value { font-size: 32px; font-weight: bold; color: #06B6D4; }
    .stat-label { font-size: 12px; color: #666; text-transform: uppercase; letter-spacing: 1px; }
    .day-section { page-break-inside: avoid; margin-bottom: 40px; border: 2px solid #e0e0e0; border-radius: 12px; overflow: hidden; }
    .day-header { padding: 20px; color: white; font-size: 24px; font-weight: bold; }
    .day-content { padding: 20px; background: white; }
    .activity { display: flex; margin-bottom: 25px; padding-bottom: 25px; border-bottom: 1px solid #e0e0e0; page-break-inside: avoid; }
    .activity:last-child { border-bottom: none; }
    .activity-number { width: 40px; height: 40px; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-weight: bold; color: white; flex-shrink: 0; margin-right: 20px; }
    .activity-details { flex: 1; }
    .activity-name { font-size: 18px; font-weight: 600; color: #1a1a1a; margin-bottom: 5px; }
    .activity-description { font-size: 14px; color: #555; line-height: 1.5; }
    .activity-badge { display: inline-block; padding: 4px 12px; border-radius: 20px; font-size: 11px; font-weight: 500; margin-right: 8px; margin-top: 8px; }
    .badge-timeSlot { background: #e3f2fd; color: #1976d2; }
    .badge-category { background: #f3e5f5; color: #7b1fa2; }
    .footer { margin-top: 60px; text-align: center; padding-top: 20px; border-top: 2px solid #e0e0e0; font-size: 12px; color: #888; }
    .footer strong { color: #06B6D4; }
  </style>
</head>
<body>
  <div class="header">
    <h1>${name || 'My Trip'}</h1>
    <div class="dates">${formatDate(startDate)} - ${formatDate(endDate)}</div>
    ${description ? `<div style="font-size:14px;color:#888;max-width:600px;margin:0 auto;">${description}</div>` : ''}
  </div>
  <div class="stats">
    <div class="stat-item"><div class="stat-value">${days.length}</div><div class="stat-label">Days</div></div>
    <div class="stat-item"><div class="stat-value">${new Set(days.map(d => d.destinationIndex)).size}</div><div class="stat-label">Destinations</div></div>
    <div class="stat-item"><div class="stat-value">${days.reduce((sum, d) => sum + (d.activities?.length || 0), 0)}</div><div class="stat-label">Activities</div></div>
  </div>
`;

  // Add each day
  days.forEach((day, dayIndex) => {
    const destination = destinations[day.destinationIndex];
    const dayColor = dayColors[dayIndex % dayColors.length];

    html += `
  <div class="day-section">
    <div class="day-header" style="background: linear-gradient(135deg, ${dayColor} 0%, ${dayColor}dd 100%);">
      Day ${day.dayNumber}: ${destination?.name || 'Unknown'}
      <div style="font-size: 14px; font-weight: normal; opacity: 0.9; margin-top: 5px;">${day.date ? formatDate(day.date) : ''}</div>
    </div>
    <div class="day-content">
`;

    day.activities?.forEach((activity, actIndex) => {
      html += `
      <div class="activity">
        <div class="activity-number" style="background: ${dayColor};">${actIndex + 1}</div>
        <div class="activity-details">
          <div class="activity-name">${activity.name}</div>
          ${activity.description ? `<div class="activity-description">${activity.description}</div>` : ''}
          <div>
            ${activity.timeSlot ? `<span class="activity-badge badge-timeSlot">${activity.timeSlot}</span>` : ''}
            ${activity.category ? `<span class="activity-badge badge-category">${activity.category}</span>` : ''}
          </div>
        </div>
      </div>
`;
    });

    if (day.notes) {
      html += `
      <div style="margin-top:20px;padding:15px;background:#fffbea;border-left:4px solid #F59E0B;font-size:14px;font-style:italic;color:#555;">
        ${day.notes}
      </div>
`;
    }

    html += `
    </div>
  </div>
`;
  });

  html += `
  <div class="footer">
    <p>Created with <strong>Prayana AI</strong> - Your Intelligent Trip Planner</p>
    <p style="margin-top: 10px;">Generated on ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
  </div>
</body>
</html>
`;

  return html;
}

/**
 * Request server-side PDF generation
 */
export async function requestPDFExport(trip) {
  try {
    const htmlContent = generatePDFHTML(trip);

    const response = await makeAPICall('/trip/export-pdf', {
      method: 'POST',
      body: JSON.stringify({
        tripId: trip.tripId,
        html: htmlContent,
      }),
    });

    if (response?.success && response.data?.pdfUrl) {
      return { success: true, pdfUrl: response.data.pdfUrl, method: 'server' };
    }

    // Fallback: return HTML for client-side rendering
    return { success: true, html: htmlContent, method: 'client' };
  } catch (error) {
    console.error('PDF export failed:', error);
    // Still return HTML so app layer can handle it
    return { success: true, html: generatePDFHTML(trip), method: 'client' };
  }
}

export const shareExportAPI = {
  generateShareLink,
  generateICalendar,
  generatePDFHTML,
  requestPDFExport,
};
