// utils/countryCodes.js - Country Code Data with Currency Information
export const COUNTRY_CODES = [
  { code: "+91", country: "IN", name: "India", flag: "🇮🇳", currency: "INR", currencySymbol: "₹" },
  { code: "+1", country: "US", name: "United States", flag: "🇺🇸", currency: "USD", currencySymbol: "$" },
  { code: "+44", country: "GB", name: "United Kingdom", flag: "🇬🇧", currency: "GBP", currencySymbol: "£" },
  { code: "+1", country: "CA", name: "Canada", flag: "🇨🇦", currency: "CAD", currencySymbol: "C$" },
  { code: "+61", country: "AU", name: "Australia", flag: "🇦🇺", currency: "AUD", currencySymbol: "A$" },
  { code: "+49", country: "DE", name: "Germany", flag: "🇩🇪", currency: "EUR", currencySymbol: "€" },
  { code: "+33", country: "FR", name: "France", flag: "🇫🇷", currency: "EUR", currencySymbol: "€" },
  { code: "+39", country: "IT", name: "Italy", flag: "🇮🇹", currency: "EUR", currencySymbol: "€" },
  { code: "+34", country: "ES", name: "Spain", flag: "🇪🇸", currency: "EUR", currencySymbol: "€" },
  { code: "+31", country: "NL", name: "Netherlands", flag: "🇳🇱", currency: "EUR", currencySymbol: "€" },
  { code: "+41", country: "CH", name: "Switzerland", flag: "🇨🇭", currency: "CHF", currencySymbol: "Fr" },
  { code: "+46", country: "SE", name: "Sweden", flag: "🇸🇪", currency: "SEK", currencySymbol: "kr" },
  { code: "+47", country: "NO", name: "Norway", flag: "🇳🇴", currency: "NOK", currencySymbol: "kr" },
  { code: "+45", country: "DK", name: "Denmark", flag: "🇩🇰", currency: "DKK", currencySymbol: "kr" },
  { code: "+358", country: "FI", name: "Finland", flag: "🇫🇮", currency: "EUR", currencySymbol: "€" },
  { code: "+43", country: "AT", name: "Austria", flag: "🇦🇹", currency: "EUR", currencySymbol: "€" },
  { code: "+32", country: "BE", name: "Belgium", flag: "🇧🇪", currency: "EUR", currencySymbol: "€" },
  { code: "+48", country: "PL", name: "Poland", flag: "🇵🇱", currency: "PLN", currencySymbol: "zł" },
  { code: "+351", country: "PT", name: "Portugal", flag: "🇵🇹", currency: "EUR", currencySymbol: "€" },
  { code: "+30", country: "GR", name: "Greece", flag: "🇬🇷", currency: "EUR", currencySymbol: "€" },
  { code: "+353", country: "IE", name: "Ireland", flag: "🇮🇪", currency: "EUR", currencySymbol: "€" },
  { code: "+420", country: "CZ", name: "Czech Republic", flag: "🇨🇿", currency: "CZK", currencySymbol: "Kč" },
  { code: "+36", country: "HU", name: "Hungary", flag: "🇭🇺", currency: "HUF", currencySymbol: "Ft" },
  { code: "+40", country: "RO", name: "Romania", flag: "🇷🇴", currency: "RON", currencySymbol: "lei" },
  { code: "+359", country: "BG", name: "Bulgaria", flag: "🇧🇬", currency: "BGN", currencySymbol: "лв" },
  { code: "+385", country: "HR", name: "Croatia", flag: "🇭🇷", currency: "EUR", currencySymbol: "€" },
  { code: "+386", country: "SI", name: "Slovenia", flag: "🇸🇮", currency: "EUR", currencySymbol: "€" },
  { code: "+421", country: "SK", name: "Slovakia", flag: "🇸🇰", currency: "EUR", currencySymbol: "€" },
  { code: "+370", country: "LT", name: "Lithuania", flag: "🇱🇹", currency: "EUR", currencySymbol: "€" },
  { code: "+371", country: "LV", name: "Latvia", flag: "🇱🇻", currency: "EUR", currencySymbol: "€" },
  { code: "+372", country: "EE", name: "Estonia", flag: "🇪🇪", currency: "EUR", currencySymbol: "€" },
  { code: "+354", country: "IS", name: "Iceland", flag: "🇮🇸", currency: "ISK", currencySymbol: "kr" },
  { code: "+352", country: "LU", name: "Luxembourg", flag: "🇱🇺", currency: "EUR", currencySymbol: "€" },
  { code: "+356", country: "MT", name: "Malta", flag: "🇲🇹", currency: "EUR", currencySymbol: "€" },
  { code: "+357", country: "CY", name: "Cyprus", flag: "🇨🇾", currency: "EUR", currencySymbol: "€" },
  { code: "+7", country: "RU", name: "Russia", flag: "🇷🇺", currency: "RUB", currencySymbol: "₽" },
  { code: "+86", country: "CN", name: "China", flag: "🇨🇳", currency: "CNY", currencySymbol: "¥" },
  { code: "+81", country: "JP", name: "Japan", flag: "🇯🇵", currency: "JPY", currencySymbol: "¥" },
  { code: "+82", country: "KR", name: "South Korea", flag: "🇰🇷", currency: "KRW", currencySymbol: "₩" },
  { code: "+65", country: "SG", name: "Singapore", flag: "🇸🇬", currency: "SGD", currencySymbol: "S$" },
  { code: "+60", country: "MY", name: "Malaysia", flag: "🇲🇾", currency: "MYR", currencySymbol: "RM" },
  { code: "+66", country: "TH", name: "Thailand", flag: "🇹🇭", currency: "THB", currencySymbol: "฿" },
  { code: "+62", country: "ID", name: "Indonesia", flag: "🇮🇩", currency: "IDR", currencySymbol: "Rp" },
  { code: "+63", country: "PH", name: "Philippines", flag: "🇵🇭", currency: "PHP", currencySymbol: "₱" },
  { code: "+84", country: "VN", name: "Vietnam", flag: "🇻🇳", currency: "VND", currencySymbol: "₫" },
  { code: "+852", country: "HK", name: "Hong Kong", flag: "🇭🇰", currency: "HKD", currencySymbol: "HK$" },
  { code: "+886", country: "TW", name: "Taiwan", flag: "🇹🇼", currency: "TWD", currencySymbol: "NT$" },
  { code: "+94", country: "LK", name: "Sri Lanka", flag: "🇱🇰", currency: "LKR", currencySymbol: "Rs" },
  { code: "+92", country: "PK", name: "Pakistan", flag: "🇵🇰", currency: "PKR", currencySymbol: "Rs" },
  { code: "+880", country: "BD", name: "Bangladesh", flag: "🇧🇩", currency: "BDT", currencySymbol: "৳" },
  { code: "+977", country: "NP", name: "Nepal", flag: "🇳🇵", currency: "NPR", currencySymbol: "Rs" },
  { code: "+975", country: "BT", name: "Bhutan", flag: "🇧🇹", currency: "BTN", currencySymbol: "Nu." },
  { code: "+960", country: "MV", name: "Maldives", flag: "🇲🇻", currency: "MVR", currencySymbol: "Rf" },
  { code: "+971", country: "AE", name: "UAE", flag: "🇦🇪", currency: "AED", currencySymbol: "د.إ" },
  { code: "+966", country: "SA", name: "Saudi Arabia", flag: "🇸🇦", currency: "SAR", currencySymbol: "﷼" },
  { code: "+974", country: "QA", name: "Qatar", flag: "🇶🇦", currency: "QAR", currencySymbol: "﷼" },
  { code: "+965", country: "KW", name: "Kuwait", flag: "🇰🇼", currency: "KWD", currencySymbol: "د.ك" },
  { code: "+973", country: "BH", name: "Bahrain", flag: "🇧🇭", currency: "BHD", currencySymbol: ".د.ب" },
  { code: "+968", country: "OM", name: "Oman", flag: "🇴🇲", currency: "OMR", currencySymbol: "﷼" },
  { code: "+98", country: "IR", name: "Iran", flag: "🇮🇷", currency: "IRR", currencySymbol: "﷼" },
  { code: "+964", country: "IQ", name: "Iraq", flag: "🇮🇶", currency: "IQD", currencySymbol: "ع.د" },
  { code: "+962", country: "JO", name: "Jordan", flag: "🇯🇴", currency: "JOD", currencySymbol: "د.ا" },
  { code: "+961", country: "LB", name: "Lebanon", flag: "🇱🇧", currency: "LBP", currencySymbol: "£" },
  { code: "+963", country: "SY", name: "Syria", flag: "🇸🇾", currency: "SYP", currencySymbol: "£" },
  { code: "+90", country: "TR", name: "Turkey", flag: "🇹🇷", currency: "TRY", currencySymbol: "₺" },
  { code: "+972", country: "IL", name: "Israel", flag: "🇮🇱", currency: "ILS", currencySymbol: "₪" },
  { code: "+20", country: "EG", name: "Egypt", flag: "🇪🇬", currency: "EGP", currencySymbol: "£" },
  { code: "+27", country: "ZA", name: "South Africa", flag: "🇿🇦", currency: "ZAR", currencySymbol: "R" },
  { code: "+234", country: "NG", name: "Nigeria", flag: "🇳🇬", currency: "NGN", currencySymbol: "₦" },
  { code: "+254", country: "KE", name: "Kenya", flag: "🇰🇪", currency: "KES", currencySymbol: "KSh" },
  { code: "+233", country: "GH", name: "Ghana", flag: "🇬🇭", currency: "GHS", currencySymbol: "₵" },
  { code: "+55", country: "BR", name: "Brazil", flag: "🇧🇷", currency: "BRL", currencySymbol: "R$" },
  { code: "+52", country: "MX", name: "Mexico", flag: "🇲🇽", currency: "MXN", currencySymbol: "$" },
  { code: "+54", country: "AR", name: "Argentina", flag: "🇦🇷", currency: "ARS", currencySymbol: "$" },
  { code: "+56", country: "CL", name: "Chile", flag: "🇨🇱", currency: "CLP", currencySymbol: "$" },
  { code: "+57", country: "CO", name: "Colombia", flag: "🇨🇴", currency: "COP", currencySymbol: "$" },
  { code: "+51", country: "PE", name: "Peru", flag: "🇵🇪", currency: "PEN", currencySymbol: "S/" },
  { code: "+58", country: "VE", name: "Venezuela", flag: "🇻🇪", currency: "VES", currencySymbol: "Bs.S" },
  { code: "+64", country: "NZ", name: "New Zealand", flag: "🇳🇿", currency: "NZD", currencySymbol: "NZ$" },
];

export const getCountryByCode = (code) => {
  return (
    COUNTRY_CODES.find((country) => country.code === code) || COUNTRY_CODES[0]
  );
};

export const formatPhoneNumber = (countryCode, phoneNumber) => {
  // Remove any existing country code or special characters
  const cleanNumber = phoneNumber.replace(/[^\d]/g, "");
  return `${countryCode}${cleanNumber}`;
};
